server:
  port: 8082

spring:
  application:
    name: auth-service

auth:
  token:
    secret: M2I1OWExNzFlNGRhOWRiMGZiM2FlM2E1ZjFkM2E4ZDI4YTg5ZTgwMjk0MmY1OGYyMzk0ZGVjYmY=
    access:
      expirationTime: 3600
    refresh:
      expirationTime: 2592000